import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Temporary placeholder values - we'll handle dynamic logic later
    const showLeftSidebar = true; // Replace with logic later
    const showRightSidebar = true; // Replace with logic later
    const leftSidebarCollapsed = false; // Replace with logic later
    const rightSidebarCollapsed = false; // Replace with logic later
    const sessionStatus = { active: false, user: undefined }; // Placeholder - fetch later

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex justify-center bg-black text-white min-h-screen">
                    {showLeftSidebar && <LeftSidebar collapsed={leftSidebarCollapsed} sessionStatus={sessionStatus} />}
                    <main className="max-w-[600px] w-full h-screen overflow-y-auto">
                        {children}
                    </main>
                    {showRightSidebar && <RightSidebar collapsed={rightSidebarCollapsed} />}
                </div>
            </body>
        </html>
    );
}
