import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // For now, using a placeholder sessionStatus
    // We'll implement proper session handling in the next step
    const sessionStatus = { active: false, user: undefined };

    return (
        <html lang="en">
            <body>
                <div className="flex justify-center bg-black text-white min-h-screen">
                    <div className="hidden md:block">
                        <LeftSidebar sessionStatus={sessionStatus} />
                    </div>

                    <main className="max-w-[600px] w-full h-screen overflow-y-auto">
                        {children}
                    </main>
                    <div className="hidden lg:block">
                        <RightSidebar />
                    </div>
                </div>
            </body>
        </html>
    );
}
