import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LayoutContent from "@/components/layoutContent";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // For now, using a placeholder sessionStatus
    // We'll implement proper session handling in the next step
    const sessionStatus = { active: false, user: undefined };

    return (
        <html lang="en">
            <body>
                <LayoutContent sessionStatus={sessionStatus}>
                    {children}
                </LayoutContent>
            </body>
        </html>
    );
}
